services:
  # Main service
  netcdf-api:
    build: .
    develop:
      watch:
        - action: rebuild
          path: ./src
    container_name: netcdf-api
    command: netcdf_api
    ports:
      - 80:80

  # For IDE use only
  netcdf-api-ide:
    build:
      context: .
      target: dev_environment
    container_name: netcdf-api-ide
    command: sleep infinity   # Keep container running
    volumes:
      - ./src:/usr/src/app
    
    