services:
  # Main service
  app:
    build: .
    container_name: netcdf-api
    command: netcdf_api
    ports:
      - 80:80

  # For IDE use only
  app_dev:
    build:
      context: .
      target: builder
    container_name: netcdf-api-builder
    command: tail -F /dev/null   # Keep container running
    volumes:
      - ./src:/usr/src/app
    
    