[tool.poetry]
name = "netcdf-challenge"
version = "0.1.0"
description = ""
authors = ["Bob Kocisko <rkocisko@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
netcdf4 = "^1.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
